/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package itson.ticketwizard.presentacion;

import itson.ticketwizard.control.BoletoControl;
import itson.ticketwizard.entidades.Boleto;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.SwingUtilities;

/**
 *
 * @author Dana Chavez
 */
public class BoletoForm extends javax.swing.JFrame {
    
    private BoletoControl boletoControl;
    private JComboBox<Boleto> comboBoxBoletos;
    private JButton btnSeleccionar;

    /**
     * Creates new form BoletoForm
     */
    public BoletoForm() {
        this.boletoControl = new BoletoControl();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarBoletosDisponibles() {
        // Obtener la lista de boletos disponibles desde el controlador
        List<Boleto> boletos = boletoControl.obtenerBoletosDisponibles(1); // Cambia el ID del evento según sea necesario

        // Limpiar el JComboBox antes de agregar nuevos elementos
        comboBoxBoletos.removeAllItems();

        // Agregar los boletos al JComboBox
        for (Boleto boleto : boletos) {
            comboBoxBoletos.addItem(boleto);
        }
    }

    public static void main(String[] args) {
        // Ejecutar la interfaz gráfica en el hilo de despacho de eventos de Swing
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new BoletoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
